server:
  port: 83
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java19
    username: root
    password: 123456
  mvc:
    format:
      date: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
    #格式JSON输出
    serialization:
      indent-output: true
    jpa:
      #显示sql
      show-sql: true
      hibernate:
        ddl-auto: update
